### ISSUE TITLE
Error compile on latest mainline Nginx 1.23

### ISSUE THREAD

**Issue by masarinetwork** [ip2location/ip2location-nginx#16]
make[1]: Entering directory `/usr/src/nginx-1.23.0'
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
        -o objs/addon/ip2location-nginx/ngx_http_ip2location_module.o \
        /usr/src/ip2location-nginx/ngx_http_ip2location_module.c
/usr/src/ip2location-nginx/ngx_http_ip2location_module.c: In function ‘ngx_http_ip2location_get_records’:
/usr/src/ip2location-nginx/ngx_http_ip2location_module.c:315:8: error: assignment from incompatible pointer type [-Werror]
   xfwd = &r->headers_in.x_forwarded_for;
        ^
/usr/src/ip2location-nginx/ngx_http_ip2location_module.c:318:4: error: passing argument 3 of ‘ngx_http_get_forwarded_addr’ from incompatible pointer type [-Werror]
    (void) ngx_http_get_forwarded_addr(r, &addr, xfwd, NULL, gcf->proxies, gcf->proxy_recursive);
    ^
In file included from src/http/ngx_http.h:36:0,
                 from /usr/src/ip2location-nginx/ngx_http_ip2location_module.c:10:
src/http/ngx_http_core_module.h:531:11: note: expected ‘struct ngx_table_elt_t *’ but argument is of type ‘struct ngx_array_t *’
 ngx_int_t ngx_http_get_forwarded_addr(ngx_http_request_t *r, ngx_addr_t *addr,
           ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/ip2location-nginx/ngx_http_ip2location_module.o] Error 1
make[1]: Leaving directory `/usr/src/nginx-1.23.0'
make: *** [modules] Error 2

**Comment by konkhra** [comment]
I receive the same error as **[masarinetwork](https://github.com/masarinetwork)** when compiling nginx 1.23

**Comment by ip2location-com** [comment]
This error is fixed with the latest commit.
